function data = loadbottle_data(fname);
%function data = loadbottle_data(fname);
  
  a = textread(fname);
  lat = -abs(a(:,1));
  lon = a(:,2);
  day = a(:,3);
  month = a(:,4);
  year = a(:,5);
  hour = a(:,6);
  minute = a(:,7);
  station = a(:,8);
  cast = a(:,9);
  depth = a(:,10);
  value = a(:,11);
  particle_size = a(:,12);
  clear a

  data = struct('FileName',fname, ...
		'year',year, ...
		'month',month, ...
		'day',day, ...
		'hour',hour, ...
		'minute',minute, ...
		'lon',lon, ...
		'lat',lat, ...
		'depth',depth, ...
		'station',station, ...
		'cast',cast, ...
		'particleSize',particle_size, ...
		'chlaValue',value);
  
  return
